name: example
description: Basic example
version: 1.1.0
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: 3.35.2

dependencies:
  flutter:
    sdk: flutter

  umvvm: ^1.3.1

  dio: ^5.9.0
  dart_mappable: ^4.6.0

dev_dependencies:
  build: ^3.0.0
  build_config: ^1.1.2
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  dart_mappable_builder: ^4.6.0
  analyzer: ^7.7.1

  umvvm_generator: ^2.1.0

flutter:
  uses-material-design: true