name: example
description: Basic example
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  umvvm: ^1.2.3

  dio: ^5.8.0
  dart_mappable: ^4.5.0

dependency_overrides:
  source_gen: ^3.0.0
  build: ^3.0.0

dev_dependencies:
  umvvm_generator: ^2.0.0

  build: ^3.0.0
  build_config: ^1.1.2
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true