name: umvvm

description: This library contains components for MVVM architecture, and also utility classes for http, navigation and di

version: 1.2.5+2

repository: https://github.com/red-collar-dev/umvvm
issue_tracker: https://github.com/red-collar-dev/umvvm/issues
documentation: https://github.com/red-collar-dev/umvvm/tree/main/packages/umvvm/doc
topics: [mvvm, state-management, di, navigation, http]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.9.0
  async: ^2.13.0
  visibility_detector: ^0.4.0+2
  universal_platform: ^1.1.0

dev_dependencies:
  build_runner: ^2.6.0
  build_config: ^1.1.2
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1

  test: any
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter

flutter:

