name: flutter_kore_generator

description: Source generators for flutter_kore architecture library annotations

version: 2.3.0

repository: https://github.com/red-collar-official/flutter_kore
issue_tracker: https://github.com/red-collar-official/flutter_kore/issues
documentation: https://github.com/red-collar-official/flutter_kore/tree/main/packages/flutter_kore/doc
topics: [state-management, di, navigation, http, codegen]

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  glob: ^2.1.3
  source_gen: ^4.0.2
  logging: ^1.3.0
  build: ^4.0.0
  path: ^1.9.1
  analyzer: ^8.3.0
  flutter_kore: ^1.4.0

dev_dependencies:
  build_runner: ^2.9.0
  build_config: ^1.2.0
  flutter_lints: ^6.0.0
  build_test: ^3.4.1
  test: ^1.26.3
flutter:
