name: umvvm_template
description: "Template project for Umvvm architecture"

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter

  # place dependencies in alphabetical order

  cupertino_icons: ^1.0.8
  dart_mappable: ^4.6.1
  intl: ^0.20.2

  umvvm: ^1.3.1

  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build: ^3.0.0
  build_config: ^1.2.0
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.6.0
  flutter_lints: ^6.0.0

  umvvm_generator: ^2.1.0

flutter:
  generate: true
  
  # assets: 
    # - assets/images/
    # - assets/svg/
    # - assets/fonts/

  uses-material-design: true
