name: sample_navigation
description: Basic sample demonstating minimal setup for umvvm - here we are using http, DI, and navigation components.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  umvvm: ^1.1.1

  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  umvvm_generator: ^2.0.0

  json_serializable:
  build: ^3.0.0
  build_config: ^1.1.2
  build_runner: ^2.6.0
  freezed: ^3.2.0
  flutter_lints: ^6.0.0
  test:

flutter:
  uses-material-design: true