name: sample_navigation
description: Basic sample demonstating minimal setup for umvvm - here we are using http, DI, and navigation components.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  umvvm: ^1.0.1

  dio: ^5.8.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter

  umvvm_generator: ^1.0.1

  json_serializable:
  build: ^2.4.2
  build_config: ^1.1.2
  build_runner: ^2.4.15
  freezed: ^2.5.8
  flutter_lints: ^3.0.2
  test:

flutter:
  uses-material-design: true