name: sample_navigation
description: Basic sample demonstating minimal setup for flutter_kore - here we are using http, DI, and navigation components.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_kore: ^1.4.3

  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_kore_generator: ^2.3.0

  json_serializable:
  build: ^4.0.2
  build_config: ^1.2.0
  build_runner: ^2.9.0
  freezed: ^3.2.3
  flutter_lints: ^6.0.0
  test:

flutter:
  uses-material-design: true